### ISSUE TITLE
why there compile with android platform always rise a exception problem?

### ISSUE THREAD

**Issue by chenyusolar** [svanas/delphereum#66] opened 2023-10-26 23:12 UTC
with this compiled to android (both 32 and 64) platform, it always stop by a exception error!

**Comment by svanas** [comment] 2023-10-27 08:01
What exception? Please be more specific.

**Comment by svanas** [comment] 2023-11-12 13:34
Closing because (a) we cannot reproduce and (b) we did not hear back from the OP

**Closed by svanas** 2023-11-12 13:34 UTC
